vich_uploader:
    db_driver: orm

    mappings:
        users:
            uri_prefix: /images/uploads/users
            upload_destination: '%kernel.project_dir%/public/images/uploads/users'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        projets:
            uri_prefix: /images/uploads/projets
            upload_destination: '%kernel.project_dir%/public/images/uploads/projets'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true